# Generated by Django 5.0.4 on 2024-04-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_delete_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forgot_password_token",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
