# Generated by Django 5.0.4 on 2024-04-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=20)),
                ("available_products", models.CharField(blank=True, max_length=40)),
                ("delivery_time", models.DateTimeField()),
                ("discount", models.CharField(blank=True, max_length=2)),
                ("in_store_prices", models.BooleanField(default=True)),
                ("shop_logo", models.ImageField(upload_to="shop_logos/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shopcategory",
                    ),
                ),
            ],
        ),
    ]
