# Generated by Django 5.0.4 on 2024-04-22 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_remove_shop_delivery_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shop",
            old_name="available_products",
            new_name="description",
        ),
    ]
