# Generated by Django 5.0.4 on 2024-04-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_rename_available_products_shop_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="description",
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
