# Generated by Django 5.0.4 on 2024-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_shop_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="shop_logo",
            field=models.ImageField(upload_to="static/shop_logos/"),
        ),
    ]
