# Generated by Django 5.0.4 on 2024-04-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_shop_shop_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="shop_logo",
            field=models.CharField(),
        ),
    ]
