# Generated by Django 5.0.4 on 2024-04-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_shop_shop_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="logo",
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name="shop",
            name="shop_logo",
            field=models.ImageField(upload_to="shop_logos/"),
        ),
    ]
