# Generated by Django 5.0.4 on 2024-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_remove_shop_shop_logo_alter_shop_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopcategory",
            name="logo",
            field=models.CharField(null=True),
        ),
    ]
