# Generated by Django 5.0.4 on 2024-04-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_shopcategory_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shop",
            name="logo",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopcategory",
            name="logo",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shopcategory",
            name="title",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
