# Generated by Django 5.0.4 on 2024-04-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="logo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
