# Generated by Django 5.0.4 on 2024-04-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_product_description_alter_product_m_qty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
