# Generated by Django 5.0.4 on 2024-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_remove_product_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
