# Generated by Django 5.0.4 on 2024-04-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_product_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="details",
        ),
        migrations.AddField(
            model_name="product",
            name="directions",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ingredients",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
