# Generated by Django 5.0.4 on 2024-04-24 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_rename_description_product_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSubCat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productcategory",
            name="subcat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productsubcat",
            ),
        ),
    ]
