# Generated by Django 5.0.4 on 2024-04-24 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_productsubcat_productcategory_subcat"),
        ("shop", "0010_alter_shop_logo_alter_shopcategory_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productsubcat",
            ),
        ),
        migrations.AddField(
            model_name="productsubcat",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.shop",
            ),
        ),
    ]
